### ISSUE TITLE
Deduplication Errors

### ISSUE THREAD

**Issue by aledavini7** [larryns/MitoScape#2]
Hello,
I am trying to use MitoScape following the instructions available on github. I have cloned the repository and I have typed the command "sbt assembly" to generate the fat jar. I am working with Java=8 as suggested in the buld.sbt file.

When I run the command I obtain a long list of errors saying: "deduplicate: different file contents found in the following:"

I copy below few lines as example:

[error] deduplicate: different file contents found in the following:
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar:com/sun/xml/bind/v2/runtime/reflect/TransducedAccessor.class
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/2.3.2/jaxb-runtime-2.3.2.jar:com/sun/xml/bind/v2/runtime/reflect/TransducedAccessor.class
[error] deduplicate: different file contents found in the following:
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar:com/sun/xml/bind/v2/runtime/reflect/opt/AccessorInjector.class
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/2.3.2/jaxb-runtime-2.3.2.jar:com/sun/xml/bind/v2/runtime/reflect/opt/AccessorInjector.class
...
...
[error] deduplicate: different file contents found in the following:
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar:javax/ws/rs/core/SecurityContext.class
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/jakarta/ws/rs/jakarta.ws.rs-api/2.1.6/jakarta.ws.rs-api-2.1.6.jar:javax/ws/rs/core/SecurityContext.class
[error] deduplicate: different file contents found in the following:
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar:javax/ws/rs/core/StreamingOutput.class
[error] /hpcnfs/home/ieo5898/.cache/coursier/v1/https/repo1.maven.org/maven2/jakarta/ws/rs/jakarta.ws.rs-api/2.1.6/jakarta.ws.rs-api-2.1.6.jar:javax/ws/rs/core/StreamingOutput.class
...
...

Is there perhaps some adjustment I have to make in the build.sbt "assemblyMergeStrategy"?

Thank you a lot!
Alessandro

**Comment by larryns** [comment]
Hi Alessandro,

Yes, the fat jar is a pain to create. There have been some upgrades to sbt and associate plugins and unfortunately with those, the fat jar build won't work. I have updated the config files, so try cloning the git again and trying the assembly again. It should work now.

In the future I won't be supporting the fat jar, just the Docker image (maybe Singularity). So keep that in mind.

Let me know if the new changes work for you.

Thanks,
Larry.

**Comment by aledavini7** [comment]
Thank you very much for the quick reply. 
I have cloned the git, tried the assembly again and now everything work!

Thank you!
Alessandro
