### ISSUE TITLE
document link  disabled

### ISSUE THREAD

**Issue by xiucz** [larryns/MitoScape#5]
Hi, 
the link https://cavatica.sbgenomics.com/public/apps#d3b-bixu/app-publisher/mitoscape-wf/ has gone wrong, can you fix it ? Thank you.
Best, 
xiucz.

**Comment by larryns** [comment]
Hi xiucz,

There was a small update in the url. Try: https://cavatica.sbgenomics.com/public/apps/d3b-bixu/app-publisher/mitoscape-wf You also have to create an account in cavatica before you can access the URL.

Thanks,
Larry.

**Comment by larryns** [comment]
I'm closing this issue, but if it persists, let me know.
